---
- name: Configuring Vector
  ansible.builtin.template:
    src: vector.yml.j2
    dest: vector.yml
    mode: "644"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_gid }}"
    validate: vector validate --no-environment --config-yaml %s
  notify: start_vector