---
# tasks file for vector-role

- name: Create directory for distr
  ansible.builtin.file:
    path: "{{ vector_download_dir }}"
    state: directory
    mode: '755'
- name: Get vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_ver }}/vector-{{ vector_ver }}-x86_64-unknown-linux-musl.tar.gz"
    dest: "{{ vector_download_dir }}/vector-{{ vector_ver }}-x86_64-unknown-linux-musl.tar.gz"
    mode: '644'
- name: Create directory for install vector
  ansible.builtin.file:
    path: "{{ vector_dir }}"
    state: directory
    mode: '755'
- name: Unpack vector
  ansible.builtin.unarchive:
    src: "{{ vector_download_dir }}/vector-{{ vector_ver }}-x86_64-unknown-linux-musl.tar.gz"
    dest: "{{ vector_dir }}"
    remote_src: true
    extra_opts: [--strip-components=2]
- name: Copy vector config
  ansible.builtin.template:
    src: "templates/vector.yaml.j2"
    dest: "{{ vector_dir }}/config/vector.yaml"
    mode: 0644
- name: Create directory for vector data
  ansible.builtin.file:
    path: "{{ vector_data }}"
    state: directory
    mode: '755'
- name: Start vector
  ansible.builtin.shell: "nohup {{ vector_dir }}/bin/vector --config {{ vector_dir }}/config/vector.yaml </dev/null 2>&1 &"
  changed_when: false