---
# tasks file for vector-role

- name: Vector Install
  include_tasks: install.yml
  tags: vector_install

- name: Configure Vector
  include_tasks: configure.yml
  tags: vector_configure

- name: Vector service create
  include_tasks: service.yml
  tags: vector_service 